<div id="footer">
  <div class="heading">Contact Us</div>
  <hr/>
  <ul class="address">
    <li>Jessie Swigger</li>
    <li><a href="mailto:jesseappwomen@gmail.com">jesseappwomen@gmail.com</a></li>
    <li>P.O. Box 245</li>
    <li>Dillsboro, NC 28725</li>
  </ul>
  <ul class="copyNotices">
    <li>This site uses the fonts Gentium Basic and DejaVu Sans.</li>
    <ul>
      <li>Gentium Basic is &copy; 2003-2005 SIL International and is licensed under the SIL Open Font License.</li>
      <li>DejaVu Sans is &copy; 2003 Bitstream, Inc. and &copy; 2006 Tavmjong Bah.</li>
    </ul>
  </ul>
</div>
