<script type="text/javascript" src="header.js"></script>
<div id="header">
  <a name="top"></a>
  <span class="primary">Appalachian Women's Museum</span>
  <ul id="links">
    <li><a href="./">Home</a></li>
    <li><a href="news.php">News</a></li>
    <li><a href="ourBoard.php">Our Board</a>
    <ul>
      <li><a href="members.php">Members</a></li>
      <li><a href="boardDocuments.php">Board Documents</a></li>
    </ul></li>
    <li><a href="ourProject.php">Our Project</a>
    <ul>
      <li><a href="history.php">History</a>
      <li><a href="meetingMinutes.php">Meeting Minutes</a></li>
      <li><a href="strategicPlan.php">Strategic Plan</a></li>
    </ul></li>
    <li><a href="videos.php">Videos</a></li>
    <li><a href="events.php">Events</a></li>
    <li><a href="support.php">Support</a></li>
  </ul>
</div>
